sudo: required

services:
  - docker

language: node_js

node_js:
  - "6.0"

cache:
  yarn: true

script:
  - "npm run lint"
  - "npm run test:cover"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker build --build-arg version=$(node -p -e "require('./package.json').version") -t index.docker.io/oshalygin/olegjs:$(node -p -e "require('./package.json').version") .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" http://index.docker.io;
      docker push index.docker.io/oshalygin/olegjs:$(node -p -e "require('./package.json').version"); else
        echo The artifact from this build was NOT pushed to a remote repository because the build is NOT on the master branch;
    fi
