apiVersion: v1
kind: Service
metadata:
    labels:
        name: web
    name: web
spec:
    type: LoadBalancer
    ports:
      - port: 80
        targetPort: 8080
        protocol: TCP
    selector:
        name: web
